name: 'Generate async docs'
description: 'https://asyncapi.com'
inputs:
  file:
    description: 'Yaml or JSON file with api specification'
    required: true
  outputDir:
    description: 'Output directory where to store generated html documentation'
    required: true
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file }}
    - ${{ inputs.outputDir }}

#  args:
#    - ${{ inputs.who-to-greet }}
