name: 'Generate async docs'
description: 'https://asyncapi.com'
inputs:
  file:
    description: 'Yaml or JSON file with api specification'
    required: true
  outputDir:
    description: 'Output directory where to store generated html documentation'
    required: true
outputs:
  docsDir:
    description: 'Directory where docs are stored'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file }}
    - ${{ inputs.outputDir }}

#  args:
#    - ${{ inputs.who-to-greet }}
